[package]
name = "todoke"
authors = ["sl91994 <112153975+sl91994@users.noreply.github.com>"]
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/sl91994/todoke"
description = "A small CLI for managing coordinated vulnerability disclosures"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive"] }
